"""empty message

Revision ID: 1c0094297b8a
Revises: 54246946783a
Create Date: 2014-09-10 07:25:18.846000

"""

# revision identifiers, used by Alembic.
revision = '1c0094297b8a'
down_revision = '54246946783a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
